{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"provenance":[{"file_id":"1gIFS_sVF1Cjs5EJWp4CPBqf7byh7HFTG","timestamp":1670904381493}],"machine_shape":"hm"},"kernelspec":{"name":"python3","display_name":"Python 3"},"language_info":{"name":"python"},"accelerator":"GPU","gpuClass":"premium"},"cells":[{"cell_type":"markdown","source":["# Convert darknet model file to tensorflow type"],"metadata":{"id":"X1-uzW98kcx6"}},{"cell_type":"markdown","source":["## AIGuysCode github clone"],"metadata":{"id":"FTwRkE-Okcgo"}},{"cell_type":"code","execution_count":1,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"KUEx-mGGMzFP","executionInfo":{"status":"ok","timestamp":1670904635547,"user_tz":-540,"elapsed":14693,"user":{"displayName":"Sy Rhee","userId":"08018339085919910006"}},"outputId":"ca8c1487-da1d-4f94-e04f-95af8244e7ec"},"outputs":[{"output_type":"stream","name":"stdout","text":["Cloning into 'tensorflow-yolov4-tflite'...\n","remote: Enumerating objects: 912, done.\u001b[K\n","remote: Total 912 (delta 0), reused 0 (delta 0), pack-reused 912\u001b[K\n","Receiving objects: 100% (912/912), 211.46 MiB | 16.48 MiB/s, done.\n","Resolving deltas: 100% (439/439), done.\n"]}],"source":["!git clone https://github.com/theAIGuysCode/tensorflow-yolov4-tflite"]},{"cell_type":"code","source":["%cd /content/tensorflow-yolov4-tflite"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"SUnb_emfM2vr","executionInfo":{"status":"ok","timestamp":1670904683934,"user_tz":-540,"elapsed":699,"user":{"displayName":"Sy Rhee","userId":"08018339085919910006"}},"outputId":"38abe61e-adff-47e5-c956-902b521f714e"},"execution_count":2,"outputs":[{"output_type":"stream","name":"stdout","text":["/content/tensorflow-yolov4-tflite\n"]}]},{"cell_type":"markdown","source":["## requirement text file 수정\n","- 필요한 오픈소스 목록 리스트업해둔 파일 \n","- requirement text 파일로 필요 오픈소스 묶음 설치하기"],"metadata":{"id":"Sg7xybAbk19O"}},{"cell_type":"code","source":["req_gpu_text = '''tensorflow-gpu==2.3.0\n","opencv-python==4.1.2.30\n","lxml\n","tqdm\n","absl-py\n","matplotlib\n","easydict\n","pillow\n","'''\n","\n","with open('requirements-gpu.txt', 'w') as f:\n","    f.write(req_gpu_text)"],"metadata":{"id":"2D8IQKMVMgPM","executionInfo":{"status":"ok","timestamp":1670904803503,"user_tz":-540,"elapsed":778,"user":{"displayName":"Sy Rhee","userId":"08018339085919910006"}}},"execution_count":3,"outputs":[]},{"cell_type":"code","source":["!pip install -r requirements-gpu.txt"],"metadata":{"colab":{"base_uri":"https://localhost:8080/","height":1000},"id":"i8umwrZ0NG0z","executionInfo":{"status":"ok","timestamp":1670904857496,"user_tz":-540,"elapsed":52134,"user":{"displayName":"Sy Rhee","userId":"08018339085919910006"}},"outputId":"e6500f41-f39f-4248-e147-f93d8fbc8cc7"},"execution_count":4,"outputs":[{"output_type":"stream","name":"stdout","text":["Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/\n","Collecting tensorflow-gpu==2.3.0\n","  Downloading tensorflow_gpu-2.3.0-cp38-cp38-manylinux2010_x86_64.whl (320.5 MB)\n","\u001b[K     |████████████████████████████████| 320.5 MB 1.3 kB/s \n","\u001b[?25hCollecting opencv-python==4.1.2.30\n","  Downloading opencv_python-4.1.2.30-cp38-cp38-manylinux1_x86_64.whl (28.3 MB)\n","\u001b[K     |████████████████████████████████| 28.3 MB 94.8 MB/s \n","\u001b[?25hRequirement already satisfied: lxml in /usr/local/lib/python3.8/dist-packages (from -r requirements-gpu.txt (line 3)) (4.9.1)\n","Requirement already satisfied: tqdm in /usr/local/lib/python3.8/dist-packages (from -r requirements-gpu.txt (line 4)) (4.64.1)\n","Requirement already satisfied: absl-py in /usr/local/lib/python3.8/dist-packages (from -r requirements-gpu.txt (line 5)) (1.3.0)\n","Requirement already satisfied: matplotlib in /usr/local/lib/python3.8/dist-packages (from -r requirements-gpu.txt (line 6)) (3.2.2)\n","Requirement already satisfied: easydict in /usr/local/lib/python3.8/dist-packages (from -r requirements-gpu.txt (line 7)) (1.10)\n","Requirement already satisfied: pillow in /usr/local/lib/python3.8/dist-packages (from -r requirements-gpu.txt (line 8)) (7.1.2)\n","Collecting gast==0.3.3\n","  Downloading gast-0.3.3-py2.py3-none-any.whl (9.7 kB)\n","Collecting scipy==1.4.1\n","  Downloading scipy-1.4.1-cp38-cp38-manylinux1_x86_64.whl (26.0 MB)\n","\u001b[K     |████████████████████████████████| 26.0 MB 1.2 MB/s \n","\u001b[?25hRequirement already satisfied: keras-preprocessing<1.2,>=1.1.1 in /usr/local/lib/python3.8/dist-packages (from tensorflow-gpu==2.3.0->-r requirements-gpu.txt (line 1)) (1.1.2)\n","Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.8/dist-packages (from tensorflow-gpu==2.3.0->-r requirements-gpu.txt (line 1)) (2.1.1)\n","Requirement already satisfied: tensorboard<3,>=2.3.0 in /usr/local/lib/python3.8/dist-packages (from tensorflow-gpu==2.3.0->-r requirements-gpu.txt (line 1)) (2.9.1)\n","Requirement already satisfied: astunparse==1.6.3 in /usr/local/lib/python3.8/dist-packages (from tensorflow-gpu==2.3.0->-r requirements-gpu.txt (line 1)) (1.6.3)\n","Requirement already satisfied: google-pasta>=0.1.8 in /usr/local/lib/python3.8/dist-packages (from tensorflow-gpu==2.3.0->-r requirements-gpu.txt (line 1)) (0.2.0)\n","Collecting h5py<2.11.0,>=2.10.0\n","  Downloading h5py-2.10.0-cp38-cp38-manylinux1_x86_64.whl (2.9 MB)\n","\u001b[K     |████████████████████████████████| 2.9 MB 85.4 MB/s \n","\u001b[?25hCollecting tensorflow-estimator<2.4.0,>=2.3.0\n","  Downloading tensorflow_estimator-2.3.0-py2.py3-none-any.whl (459 kB)\n","\u001b[K     |████████████████████████████████| 459 kB 90.7 MB/s \n","\u001b[?25hRequirement already satisfied: wrapt>=1.11.1 in /usr/local/lib/python3.8/dist-packages (from tensorflow-gpu==2.3.0->-r requirements-gpu.txt (line 1)) (1.14.1)\n","Requirement already satisfied: wheel>=0.26 in /usr/local/lib/python3.8/dist-packages (from tensorflow-gpu==2.3.0->-r requirements-gpu.txt (line 1)) (0.38.4)\n","Requirement already satisfied: protobuf>=3.9.2 in /usr/local/lib/python3.8/dist-packages (from tensorflow-gpu==2.3.0->-r requirements-gpu.txt (line 1)) (3.19.6)\n","Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.8/dist-packages (from tensorflow-gpu==2.3.0->-r requirements-gpu.txt (line 1)) (1.15.0)\n","Requirement already satisfied: grpcio>=1.8.6 in /usr/local/lib/python3.8/dist-packages (from tensorflow-gpu==2.3.0->-r requirements-gpu.txt (line 1)) (1.51.1)\n","Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.8/dist-packages (from tensorflow-gpu==2.3.0->-r requirements-gpu.txt (line 1)) (3.3.0)\n","Collecting numpy<1.19.0,>=1.16.0\n","  Downloading numpy-1.18.5-cp38-cp38-manylinux1_x86_64.whl (20.6 MB)\n","\u001b[K     |████████████████████████████████| 20.6 MB 72.2 MB/s \n","\u001b[?25hRequirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in /usr/local/lib/python3.8/dist-packages (from tensorboard<3,>=2.3.0->tensorflow-gpu==2.3.0->-r requirements-gpu.txt (line 1)) (0.4.6)\n","Requirement already satisfied: tensorboard-data-server<0.7.0,>=0.6.0 in /usr/local/lib/python3.8/dist-packages (from tensorboard<3,>=2.3.0->tensorflow-gpu==2.3.0->-r requirements-gpu.txt (line 1)) (0.6.1)\n","Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.8/dist-packages (from tensorboard<3,>=2.3.0->tensorflow-gpu==2.3.0->-r requirements-gpu.txt (line 1)) (1.0.1)\n","Requirement already satisfied: google-auth<3,>=1.6.3 in /usr/local/lib/python3.8/dist-packages (from tensorboard<3,>=2.3.0->tensorflow-gpu==2.3.0->-r requirements-gpu.txt (line 1)) (2.15.0)\n","Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in /usr/local/lib/python3.8/dist-packages (from tensorboard<3,>=2.3.0->tensorflow-gpu==2.3.0->-r requirements-gpu.txt (line 1)) (1.8.1)\n","Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.8/dist-packages (from tensorboard<3,>=2.3.0->tensorflow-gpu==2.3.0->-r requirements-gpu.txt (line 1)) (2.23.0)\n","Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.8/dist-packages (from tensorboard<3,>=2.3.0->tensorflow-gpu==2.3.0->-r requirements-gpu.txt (line 1)) (3.4.1)\n","Requirement already satisfied: setuptools>=41.0.0 in /usr/local/lib/python3.8/dist-packages (from tensorboard<3,>=2.3.0->tensorflow-gpu==2.3.0->-r requirements-gpu.txt (line 1)) (57.4.0)\n","Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.8/dist-packages (from google-auth<3,>=1.6.3->tensorboard<3,>=2.3.0->tensorflow-gpu==2.3.0->-r requirements-gpu.txt (line 1)) (4.9)\n","Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.8/dist-packages (from google-auth<3,>=1.6.3->tensorboard<3,>=2.3.0->tensorflow-gpu==2.3.0->-r requirements-gpu.txt (line 1)) (5.2.0)\n","Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.8/dist-packages (from google-auth<3,>=1.6.3->tensorboard<3,>=2.3.0->tensorflow-gpu==2.3.0->-r requirements-gpu.txt (line 1)) (0.2.8)\n","Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.8/dist-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard<3,>=2.3.0->tensorflow-gpu==2.3.0->-r requirements-gpu.txt (line 1)) (1.3.1)\n","Requirement already satisfied: importlib-metadata>=4.4 in /usr/local/lib/python3.8/dist-packages (from markdown>=2.6.8->tensorboard<3,>=2.3.0->tensorflow-gpu==2.3.0->-r requirements-gpu.txt (line 1)) (4.13.0)\n","Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.8/dist-packages (from importlib-metadata>=4.4->markdown>=2.6.8->tensorboard<3,>=2.3.0->tensorflow-gpu==2.3.0->-r requirements-gpu.txt (line 1)) (3.11.0)\n","Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /usr/local/lib/python3.8/dist-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<3,>=2.3.0->tensorflow-gpu==2.3.0->-r requirements-gpu.txt (line 1)) (0.4.8)\n","Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.8/dist-packages (from requests<3,>=2.21.0->tensorboard<3,>=2.3.0->tensorflow-gpu==2.3.0->-r requirements-gpu.txt (line 1)) (2.10)\n","Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.8/dist-packages (from requests<3,>=2.21.0->tensorboard<3,>=2.3.0->tensorflow-gpu==2.3.0->-r requirements-gpu.txt (line 1)) (1.24.3)\n","Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.8/dist-packages (from requests<3,>=2.21.0->tensorboard<3,>=2.3.0->tensorflow-gpu==2.3.0->-r requirements-gpu.txt (line 1)) (3.0.4)\n","Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.8/dist-packages (from requests<3,>=2.21.0->tensorboard<3,>=2.3.0->tensorflow-gpu==2.3.0->-r requirements-gpu.txt (line 1)) (2022.9.24)\n","Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.8/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard<3,>=2.3.0->tensorflow-gpu==2.3.0->-r requirements-gpu.txt (line 1)) (3.2.2)\n","Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.8/dist-packages (from matplotlib->-r requirements-gpu.txt (line 6)) (2.8.2)\n","Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.8/dist-packages (from matplotlib->-r requirements-gpu.txt (line 6)) (1.4.4)\n","Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.8/dist-packages (from matplotlib->-r requirements-gpu.txt (line 6)) (3.0.9)\n","Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.8/dist-packages (from matplotlib->-r requirements-gpu.txt (line 6)) (0.11.0)\n","Installing collected packages: numpy, tensorflow-estimator, scipy, h5py, gast, tensorflow-gpu, opencv-python\n","  Attempting uninstall: numpy\n","    Found existing installation: numpy 1.21.6\n","    Uninstalling numpy-1.21.6:\n","      Successfully uninstalled numpy-1.21.6\n","  Attempting uninstall: tensorflow-estimator\n","    Found existing installation: tensorflow-estimator 2.9.0\n","    Uninstalling tensorflow-estimator-2.9.0:\n","      Successfully uninstalled tensorflow-estimator-2.9.0\n","  Attempting uninstall: scipy\n","    Found existing installation: scipy 1.7.3\n","    Uninstalling scipy-1.7.3:\n","      Successfully uninstalled scipy-1.7.3\n","  Attempting uninstall: h5py\n","    Found existing installation: h5py 3.1.0\n","    Uninstalling h5py-3.1.0:\n","      Successfully uninstalled h5py-3.1.0\n","  Attempting uninstall: gast\n","    Found existing installation: gast 0.4.0\n","    Uninstalling gast-0.4.0:\n","      Successfully uninstalled gast-0.4.0\n","  Attempting uninstall: opencv-python\n","    Found existing installation: opencv-python 4.6.0.66\n","    Uninstalling opencv-python-4.6.0.66:\n","      Successfully uninstalled opencv-python-4.6.0.66\n","\u001b[31mERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.\n","xarray-einstats 0.3.0 requires numpy>=1.19, but you have numpy 1.18.5 which is incompatible.\n","xarray-einstats 0.3.0 requires scipy>=1.5, but you have scipy 1.4.1 which is incompatible.\n","tifffile 2022.10.10 requires numpy>=1.19.2, but you have numpy 1.18.5 which is incompatible.\n","tensorflow 2.9.2 requires numpy>=1.20, but you have numpy 1.18.5 which is incompatible.\n","tensorflow 2.9.2 requires tensorflow-estimator<2.10.0,>=2.9.0rc0, but you have tensorflow-estimator 2.3.0 which is incompatible.\n","tables 3.7.0 requires numpy>=1.19.0, but you have numpy 1.18.5 which is incompatible.\n","plotnine 0.8.0 requires numpy>=1.19.0, but you have numpy 1.18.5 which is incompatible.\n","plotnine 0.8.0 requires scipy>=1.5.0, but you have scipy 1.4.1 which is incompatible.\n","jaxlib 0.3.25+cuda11.cudnn805 requires numpy>=1.20, but you have numpy 1.18.5 which is incompatible.\n","jaxlib 0.3.25+cuda11.cudnn805 requires scipy>=1.5, but you have scipy 1.4.1 which is incompatible.\n","jax 0.3.25 requires numpy>=1.20, but you have numpy 1.18.5 which is incompatible.\n","jax 0.3.25 requires scipy>=1.5, but you have scipy 1.4.1 which is incompatible.\n","cupy-cuda11x 11.0.0 requires numpy<1.26,>=1.20, but you have numpy 1.18.5 which is incompatible.\n","cmdstanpy 1.0.8 requires numpy>=1.21, but you have numpy 1.18.5 which is incompatible.\u001b[0m\n","Successfully installed gast-0.3.3 h5py-2.10.0 numpy-1.18.5 opencv-python-4.1.2.30 scipy-1.4.1 tensorflow-estimator-2.3.0 tensorflow-gpu-2.3.0\n"]},{"output_type":"display_data","data":{"application/vnd.colab-display-data+json":{"pip_warning":{"packages":["numpy"]}}},"metadata":{}}]},{"cell_type":"markdown","source":["## 학습된 weight파일 및 클래스네임 파일 gdown"],"metadata":{"id":"Myv-hY0AlEXN"}},{"cell_type":"code","source":["%cd /content/tensorflow-yolov4-tflite/data"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"9RTNxCn4ORZW","executionInfo":{"status":"ok","timestamp":1670904943394,"user_tz":-540,"elapsed":499,"user":{"displayName":"Sy Rhee","userId":"08018339085919910006"}},"outputId":"1e3fdfc3-6ac7-49ab-cc03-d2d24e1c77e8"},"execution_count":5,"outputs":[{"output_type":"stream","name":"stdout","text":["/content/tensorflow-yolov4-tflite/data\n"]}]},{"cell_type":"code","source":["!pip install -U --no-cache-dir gdown --pre"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"3ezyY1EMNr7G","executionInfo":{"status":"ok","timestamp":1670904950429,"user_tz":-540,"elapsed":3709,"user":{"displayName":"Sy Rhee","userId":"08018339085919910006"}},"outputId":"4e89896d-8093-44d3-e687-8bbe6e401f6f"},"execution_count":6,"outputs":[{"output_type":"stream","name":"stdout","text":["Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/\n","Requirement already satisfied: gdown in /usr/local/lib/python3.8/dist-packages (4.4.0)\n","Collecting gdown\n","  Downloading gdown-4.6.0-py3-none-any.whl (14 kB)\n","Requirement already satisfied: requests[socks] in /usr/local/lib/python3.8/dist-packages (from gdown) (2.23.0)\n","Requirement already satisfied: tqdm in /usr/local/lib/python3.8/dist-packages (from gdown) (4.64.1)\n","Requirement already satisfied: six in /usr/local/lib/python3.8/dist-packages (from gdown) (1.15.0)\n","Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.8/dist-packages (from gdown) (4.6.3)\n","Requirement already satisfied: filelock in /usr/local/lib/python3.8/dist-packages (from gdown) (3.8.0)\n","Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.8/dist-packages (from requests[socks]->gdown) (3.0.4)\n","Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.8/dist-packages (from requests[socks]->gdown) (2022.9.24)\n","Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.8/dist-packages (from requests[socks]->gdown) (1.24.3)\n","Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.8/dist-packages (from requests[socks]->gdown) (2.10)\n","Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.8/dist-packages (from requests[socks]->gdown) (1.7.1)\n","Installing collected packages: gdown\n","  Attempting uninstall: gdown\n","    Found existing installation: gdown 4.4.0\n","    Uninstalling gdown-4.4.0:\n","      Successfully uninstalled gdown-4.4.0\n","Successfully installed gdown-4.6.0\n"]}]},{"cell_type":"code","source":["# yolov4.weights file 다운로드\n","!gdown 1wH9_mWifhShaK5LlVvRq3DKLtkLU3et9"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"4Ftnv1zvOKsn","executionInfo":{"status":"ok","timestamp":1670904955644,"user_tz":-540,"elapsed":2030,"user":{"displayName":"Sy Rhee","userId":"08018339085919910006"}},"outputId":"b7eec1a1-d50c-43c9-f709-7338c060f90d"},"execution_count":7,"outputs":[{"output_type":"stream","name":"stdout","text":["Downloading...\n","From: https://drive.google.com/uc?id=1wH9_mWifhShaK5LlVvRq3DKLtkLU3et9\n","To: /content/tensorflow-yolov4-tflite/data/yolov4-custom_best.weights\n","100% 256M/256M [00:00<00:00, 372MB/s]\n"]}]},{"cell_type":"code","source":["%cd /content/tensorflow-yolov4-tflite/data/classes"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"ZlJmIQ8-O6SU","executionInfo":{"status":"ok","timestamp":1670904967775,"user_tz":-540,"elapsed":492,"user":{"displayName":"Sy Rhee","userId":"08018339085919910006"}},"outputId":"6f80eaaa-e9bd-4c6b-9143-c2811fec3bfb"},"execution_count":8,"outputs":[{"output_type":"stream","name":"stdout","text":["/content/tensorflow-yolov4-tflite/data/classes\n"]}]},{"cell_type":"code","source":["# 구글 드라이브 파일에서 names을 colab으로 다운로드\n","!gdown 1Ea9iydXmibS1bDnlVRsPhK4E9r-yifyT"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"jHMD0hsGfTWm","executionInfo":{"status":"ok","timestamp":1670904972508,"user_tz":-540,"elapsed":1190,"user":{"displayName":"Sy Rhee","userId":"08018339085919910006"}},"outputId":"6aaba8a7-50ba-42c6-faff-3aa5a27e3e49"},"execution_count":9,"outputs":[{"output_type":"stream","name":"stdout","text":["Downloading...\n","From: https://drive.google.com/uc?id=1Ea9iydXmibS1bDnlVRsPhK4E9r-yifyT\n","To: /content/tensorflow-yolov4-tflite/data/classes/ClassNames.names\n","\r  0% 0.00/12.0 [00:00<?, ?B/s]\r100% 12.0/12.0 [00:00<00:00, 21.2kB/s]\n"]}]},{"cell_type":"code","source":["%cd /content/tensorflow-yolov4-tflite"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"tGfzfORCfWMM","executionInfo":{"status":"ok","timestamp":1670904977741,"user_tz":-540,"elapsed":591,"user":{"displayName":"Sy Rhee","userId":"08018339085919910006"}},"outputId":"ab1d23fe-33e6-418e-f44b-dc6f113c7a7e"},"execution_count":10,"outputs":[{"output_type":"stream","name":"stdout","text":["/content/tensorflow-yolov4-tflite\n"]}]},{"cell_type":"markdown","source":["##  darknet weights -> tensorflow 형식으로 변환\n","- class name 파일 경로 : custom dataset class name 파일 경로로 수정"],"metadata":{"id":"mbMyTQMXlU_u"}},{"cell_type":"code","source":["## yolov4\n","## 파일 변환 (weights 파일에서 --> output 파일로)\n","!python save_model.py --weights ./data/yolov4-custom_best.weights --output ./checkpoints/yolov4-416 --input_size 416 --model yolov4"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"mUL81WOhNtL4","executionInfo":{"status":"ok","timestamp":1670905367462,"user_tz":-540,"elapsed":6768,"user":{"displayName":"Sy Rhee","userId":"08018339085919910006"}},"outputId":"f020ff77-656a-4996-8cf7-986c95c2ec55"},"execution_count":11,"outputs":[{"output_type":"stream","name":"stdout","text":["2022-12-13 04:22:40.290354: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia\n","2022-12-13 04:22:40.290404: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.\n","2022-12-13 04:22:41.773057: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcuda.so.1\n","2022-12-13 04:22:42.435171: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2022-12-13 04:22:42.435798: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties: \n","pciBusID: 0000:00:04.0 name: Tesla T4 computeCapability: 7.5\n","coreClock: 1.59GHz coreCount: 40 deviceMemorySize: 14.75GiB deviceMemoryBandwidth: 298.08GiB/s\n","2022-12-13 04:22:42.435938: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia\n","2022-12-13 04:22:42.436476: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcublas.so.10'; dlerror: libcublas.so.10: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia\n","2022-12-13 04:22:42.456216: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10\n","2022-12-13 04:22:42.473897: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10\n","2022-12-13 04:22:42.474118: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcusolver.so.10'; dlerror: libcusolver.so.10: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia\n","2022-12-13 04:22:42.474242: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcusparse.so.10'; dlerror: libcusparse.so.10: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia\n","2022-12-13 04:22:42.474364: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudnn.so.7'; dlerror: libcudnn.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia\n","2022-12-13 04:22:42.474381: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1753] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.\n","Skipping registering GPU devices...\n","2022-12-13 04:22:42.474846: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA\n","To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n","2022-12-13 04:22:42.480297: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 2000185000 Hz\n","2022-12-13 04:22:42.480571: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x19cd500 initialized for platform Host (this does not guarantee that XLA will be used). Devices:\n","2022-12-13 04:22:42.480606: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version\n","2022-12-13 04:22:42.481694: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1257] Device interconnect StreamExecutor with strength 1 edge matrix:\n","2022-12-13 04:22:42.481724: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1263]      \n","Traceback (most recent call last):\n","  File \"save_model.py\", line 58, in <module>\n","    app.run(main)\n","  File \"/usr/local/lib/python3.8/dist-packages/absl/app.py\", line 308, in run\n","    _run_main(main, args)\n","  File \"/usr/local/lib/python3.8/dist-packages/absl/app.py\", line 254, in _run_main\n","    sys.exit(main(argv))\n","  File \"save_model.py\", line 54, in main\n","    save_tf()\n","  File \"save_model.py\", line 49, in save_tf\n","    utils.load_weights(model, FLAGS.weights, FLAGS.model, FLAGS.tiny)\n","  File \"/content/tensorflow-yolov4-tflite/core/utils.py\", line 63, in load_weights\n","    conv_weights = conv_weights.reshape(conv_shape).transpose([2, 3, 1, 0])\n","ValueError: cannot reshape array of size 4559937 into shape (1024,512,3,3)\n"]}]},{"cell_type":"markdown","source":["모델 작동 확인"],"metadata":{"id":"lY_3fPsGl64D"}},{"cell_type":"code","source":["# yolov4 tensorflow model 실행\n","!python detect.py --weights ./checkpoints/yolov4-416 --size 416 --model yolov4 --images ./data/images/mask_01.jpg"],"metadata":{"id":"SxLfIiHVP5tb","colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"status":"ok","timestamp":1670908963653,"user_tz":-540,"elapsed":3786,"user":{"displayName":"Sy Rhee","userId":"08018339085919910006"}},"outputId":"11c11b1d-3b85-4aaf-8a3a-33f0b27fc5ae"},"execution_count":12,"outputs":[{"output_type":"stream","name":"stdout","text":["2022-12-13 05:22:39.434504: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia\n","2022-12-13 05:22:39.434546: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.\n","2022-12-13 05:22:40.742409: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcuda.so.1\n","2022-12-13 05:22:41.383777: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2022-12-13 05:22:41.384444: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties: \n","pciBusID: 0000:00:04.0 name: Tesla T4 computeCapability: 7.5\n","coreClock: 1.59GHz coreCount: 40 deviceMemorySize: 14.75GiB deviceMemoryBandwidth: 298.08GiB/s\n","2022-12-13 05:22:41.384601: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia\n","2022-12-13 05:22:41.384695: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcublas.so.10'; dlerror: libcublas.so.10: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia\n","2022-12-13 05:22:41.391866: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10\n","2022-12-13 05:22:41.392247: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10\n","2022-12-13 05:22:41.392356: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcusolver.so.10'; dlerror: libcusolver.so.10: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia\n","2022-12-13 05:22:41.392438: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcusparse.so.10'; dlerror: libcusparse.so.10: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia\n","2022-12-13 05:22:41.392521: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudnn.so.7'; dlerror: libcudnn.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia\n","2022-12-13 05:22:41.392539: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1753] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.\n","Skipping registering GPU devices...\n","2022-12-13 05:22:41.468064: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA\n","To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n","2022-12-13 05:22:41.473885: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 2000185000 Hz\n","2022-12-13 05:22:41.474173: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x1ef5340 initialized for platform Host (this does not guarantee that XLA will be used). Devices:\n","2022-12-13 05:22:41.474216: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version\n","2022-12-13 05:22:41.475352: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1257] Device interconnect StreamExecutor with strength 1 edge matrix:\n","2022-12-13 05:22:41.475382: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1263]      \n","2022-12-13 05:22:41.616551: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2022-12-13 05:22:41.617358: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x1ef64c0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:\n","2022-12-13 05:22:41.617394: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Tesla T4, Compute Capability 7.5\n","2022-12-13 05:22:41.617595: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2022-12-13 05:22:41.618226: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties: \n","pciBusID: 0000:00:04.0 name: Tesla T4 computeCapability: 7.5\n","coreClock: 1.59GHz coreCount: 40 deviceMemorySize: 14.75GiB deviceMemoryBandwidth: 298.08GiB/s\n","2022-12-13 05:22:41.618377: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia\n","2022-12-13 05:22:41.618458: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcublas.so.10'; dlerror: libcublas.so.10: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia\n","2022-12-13 05:22:41.618480: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10\n","2022-12-13 05:22:41.618496: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10\n","2022-12-13 05:22:41.618551: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcusolver.so.10'; dlerror: libcusolver.so.10: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia\n","2022-12-13 05:22:41.618609: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcusparse.so.10'; dlerror: libcusparse.so.10: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia\n","2022-12-13 05:22:41.618672: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudnn.so.7'; dlerror: libcudnn.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia\n","2022-12-13 05:22:41.618687: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1753] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.\n","Skipping registering GPU devices...\n","2022-12-13 05:22:41.618716: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1257] Device interconnect StreamExecutor with strength 1 edge matrix:\n","2022-12-13 05:22:41.618732: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1263]      0 \n","2022-12-13 05:22:41.618753: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 0:   N \n","Traceback (most recent call last):\n","  File \"detect.py\", line 107, in <module>\n","    app.run(main)\n","  File \"/usr/local/lib/python3.8/dist-packages/absl/app.py\", line 308, in run\n","    _run_main(main, args)\n","  File \"/usr/local/lib/python3.8/dist-packages/absl/app.py\", line 254, in _run_main\n","    sys.exit(main(argv))\n","  File \"detect.py\", line 41, in main\n","    saved_model_loaded = tf.saved_model.load(FLAGS.weights, tags=[tag_constants.SERVING])\n","  File \"/usr/local/lib/python3.8/dist-packages/tensorflow/python/saved_model/load.py\", line 603, in load\n","    return load_internal(export_dir, tags, options)\n","  File \"/usr/local/lib/python3.8/dist-packages/tensorflow/python/saved_model/load.py\", line 614, in load_internal\n","    loader_impl.parse_saved_model_with_debug_info(export_dir))\n","  File \"/usr/local/lib/python3.8/dist-packages/tensorflow/python/saved_model/loader_impl.py\", line 56, in parse_saved_model_with_debug_info\n","    saved_model = _parse_saved_model(export_dir)\n","  File \"/usr/local/lib/python3.8/dist-packages/tensorflow/python/saved_model/loader_impl.py\", line 110, in parse_saved_model\n","    raise IOError(\"SavedModel file does not exist at: %s/{%s|%s}\" %\n","OSError: SavedModel file does not exist at: ./checkpoints/yolov4-416/{saved_model.pbtxt|saved_model.pb}\n"]}]},{"cell_type":"code","source":[],"metadata":{"id":"8wPamI8A4BUG"},"execution_count":null,"outputs":[]}]}